version: "3"
services:
  backend:
    image: maheramara/load-optimisation-backend
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    image: maheramara/load-optimisation-frontend
    build:
      context: ./frontend
      target: runner
    command: node server.js
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend