# Generated by Django 4.2.4 on 2023-08-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_type', models.CharField(choices=[('1_ton_side_grill', '1 Ton Side grill'), ('1_ton_box', '1 Ton Box'), ('3_ton_side_grill', '3 Ton Side grill'), ('3_ton_box', '3 Ton Box'), ('7_ton_side_grill', '7 Ton Side grill'), ('7_ton_box', '7 Ton Box'), ('10_ton_side_grill', '10 Ton Side grill'), ('10_ton_box', '10 Ton Box'), ('12m_flatbed_box', '12m Flatbed Box'), ('12m_flatbed_open', '12m Flatbed Open'), ('12m_flatbed_side_grill', '12m Flatbed Side grill'), ('13.60m_flatbed_side_grill', '13.60m Flatbed Side grill'), ('13.60m_side_curtain', '13.60m Side curtain'), ('13.60m_box', '13.60m Box'), ('15.60m_side_curtain', '15.60m Side curtain'), ('15.60m_box', '15.60m Box'), ('15.60m_side_grill', '15.60m Side grill'), ('14m_low_bed', '14m Low Bed'), ('12m_double_axle_heavy_duty', '12m Double Axle Heavy Duty 28 Tons')], max_length=30)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=4)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
