# Generated by Django 4.2.4 on 2023-08-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='max_weight',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
